### ISSUE TITLE
Multiple errors (clang) and warnings (clang + g++)

### ISSUE THREAD

**Issue by xtemp09** [ron4fun/HashLib4CPP#5]
Simple test program cannot be compiled with `clang`, though it's compiled with `gcc`.
A progam cannot be compiled because `gcc` does not know what memset is. `#include <string.h>` helps.
`gcc` gives the following warnings (they are all the same):

> ..\test_hash\Checksum/../Base/HlpConverters.h: In static member function 'static HashLibStringArray Converters::SplitString(const string&, char)':
> ..\test_hash\Checksum/../Base/HlpConverters.h:367:48: warning: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
>   367 |                         for (register uint32_t i = 0; i < S.length(); i += 1)
>       |                                                ^
> 	  
> 
> ..\test_hash\Hash64/HlpXXHash64.h:247:52: warning: integer constant is so large that it is unsigned
>   247 |         static const uint64_t PRIME64_2 = uint64_t(14029467366897019727);
>       |                                                    ^~~~~~~~~~~~~~~~~~~~

`clang` gives the following errors:

> ./Crypto/Blake2SConfigurations/../../Utils/HlpUtils.h:31:54: error: cannot pass object of non-trivial type 'std::basic_string<char>' through
>       variadic function; call will abort at runtime [-Wnon-pod-varargs]
>                 size_t size = snprintf(nullptr, 0, format.c_str(), args ...) + 1; // Extra space for '\0'
>                                                                    ^
> ./NullDigest/../Base/HlpHash.h:76:47: note: in instantiation of function template specialization 'Utils::string_format<std::basic_string<char>>'
>       requested here
>                 throw NotImplementedHashLibException(Utils::string_format(Hash::CloneNotYetImplemented, GetName()));

> $ clang --version
>(built by Brecht Sanders) clang version 12.0.0
>Target: x86_64-w64-windows-gnu
>Thread model: posix

>$ g++ --version
>g++ (MinGW-W64 x86_64-posix-seh, built by Brecht Sanders) 11.1.0

The test program:

`#include <iostream>`
`#include <fstream>`
`#include <string.h>`

`#include "HashLib4CPP.h"`

using namespace std;

int main(void)
{
    IHash hash = HashLib4CPP::Crypto::CreateMD5();
    hash->Initialize();

ifstream input_file ("test.txt", ifstream::in | ifstream::binary);

const size_t BufferSize = `144*7*1024`;
char buffer [BufferSize];

while (!input_file.eof())
{
input_file.read (buffer, BufferSize);
const size_t numBytesRead = size_t(i nput_file.gcount() );
hash->TransformUntyped (buffer, numBytesRead);
}

cout<< "\nMD5: "<< hash->TransformFinal()->ToString() <<'\n';

return 0;
}

**Comment by xtemp09** [comment]
To conclude, the code is outdated.

**Comment by ron4fun** [comment]
Thanks for your review. Pull requests are always welcome to fix those issues.

**Comment by ron4fun** [comment]
This here is a new upgrade of HashLib4CPP. [HashLibPlus](https://github.com/ron4fun/HashLibPlus) your feedback is always welcomed. Thanks!
